# Generated by Django 3.1.7 on 2022-01-17 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetColors',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_color', management.models.ColorField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_assetcolors_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=50, unique=True, verbose_name='Module Name')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(default=False, max_length=50, verbose_name='Display Name')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('chained_module', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_module_created', to=settings.AUTH_USER_MODEL)),
                ('parent_module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.module')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_module_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('weightage', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('asset_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_dropdown_asset_color', to='management.assetcolors')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_dropdown_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_dropdown_module', to='management.module')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_dropdown_parent', to='management.dropdown')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_dropdown_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assetcolors',
            name='dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_assetcolors_dropdown', to='management.dropdown'),
        ),
        migrations.AddField(
            model_name='assetcolors',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_assetcolors_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
