# Generated by Django 3.1.7 on 2022-01-17 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediamanager', '0001_initial'),
        ('actions', '0002_auto_20220117_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='actions_action_media_attachment', to='mediamanager.MediaAttachment'),
        ),
        migrations.AddField(
            model_name='action',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_action_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_action_status', to='management.dropdown'),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_action_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
