# Generated by Django 3.1.7 on 2022-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('actions', '0003_auto_20220117_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_action_action_category', to='management.dropdown'),
        ),
    ]
