# Generated by Django 3.1.7 on 2022-01-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20220118_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='completion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
