# Generated by Django 3.1.7 on 2022-02-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_source'),
        ('actions', '0007_action_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_action_source', to='management.source'),
        ),
    ]
