# Generated by Django 3.1.7 on 2022-01-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('accounts', '0002_user_is_instance_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.entity'),
        ),
    ]
